services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      TZ: Asia/Tokyo
      KC_DB: postgres
      KC_DB_PASSWORD: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
    command:
      - start
      # - start-dev
      # - --verbose
    ports:
      - 8080:8080
    depends_on:
      postgres: 
        condition: service_healthy
    # restart: unless-stopped

  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U keycloak
      interval: 2s
      timeout: 5s
      retries: 5
    # restart: unless-stopped
  
volumes:
  postgres_data: